### ISSUE TITLE
"What's New" section that we could utilize RSS and\or Webhooks

### ISSUE THREAD

**Issue by eddiejimenez** [ugurkocde/intunemacadmins#16]
**Is your feature request related to a problem? Please describe.**
No problem. Just a feature request. 

**Describe the solution you'd like**
Ultimately start with a what's new section. One-stop-shop for all the new features and maybe a "What's coming" section.
This would be great to have in conjunction with RSS compatibility. 

**Describe alternatives you've considered**
None

**Additional context**
Love what you all have done thus far!!

**Comment by ugurkocde** [comment]
Hi @eddiejimenez,

thanks for the feature request.

A What´s New Section sounds interisting. Let me try to add that in the next update.

Best regards
Ugur
